### PR TITLE
Submitting Format Changes 

### PR DESCRIPTION
**Pull request by kelseaflores**
- Reformatted the classes in the "storage/sis-storage/src/main/java/org/apache/sis/index/tree/" directory by changing the 2-space indentations to 4-space indentations.

- In QuadTreeWriter:
Removed the System.out.println statements. 
Removed the catch (IOException) statement and added a throws IOException in method signature instead.

### CODE REVIEW

**Comment by desruisseaux** [comment]
Hello Kelsea

Thanks for this cleaning work! But this pull request seems to contain the addition of two files (`Ex2.2.rtf` and `Ex5.8.circ`), but I do not see changes in Java classes. Could it be that the changes have not been pushed? Can you try to execute "git log" in the directory of your SIS clone and tell us the 3 or 4 first records that you see?

**Comment by kelseaflores** [comment]
Hi Martin, 

That's strange. I don't know where those files came from. When I executed "git log", here were the records that I saw: 

commit 29ffb6e9408fbd679aaaf7973e6db79f461087e5
Merge: 9e8701f f221355
Author: Kelsea Flores <kjflores2@usfca.edu>
Date:   Mon Aug 6 20:12:57 2018 -0700

    Merge https://github.com/apache/sis
    Merging master branch with my local branch.

commit f2213552e7516c40a02968776bb9462ffb928c6a
Merge: 7288315 11d4e97
Author: Martin Desruisseaux <martin.desruisseaux@geomatys.com>
Date:   Mon Aug 6 14:09:24 2018 +0200

    Merge branch 'geoapi-3.1'.

commit 11d4e97d3ee0bc7d6afe5f081ac43081530eda1d
Merge: d281917 c028527
Author: Martin Desruisseaux <martin.desruisseaux@geomatys.com>
Date:   Mon Aug 6 14:06:06 2018 +0200

    Merge branch 'geoapi-4.0' into geoapi-3.1.

commit c0285273453128352190ca5c584181a4d8a987eb

**Comment by desruisseaux** [comment]
Looking at the commit referenced in the log message, I did not found modifications in the `index/tree` files. Maybe it would be easier to restart from a fresh copy? What about the following steps?

1. Save somewhere the files that you modified in the `storage/sis-storage/src/main/java/org/apache/sis/index/tree/` directory.
2. Delete the `https://github.com/kelseaflores/sis` repository.
3. Go on `https://github.com/apache/sis` and click on the "Fork" button in the upper-right corner.
4. In the popup window, select your account. This will create a new `https://github.com/kelseaflores/sis` repository in replacement of the one we deleted in step 2.
5. Overwrite the files in the `storage/sis-storage/src/main/java/org/apache/sis/index/tree/` directory with the ones that you saved at step 1.
6. Execute `git add -u`, then `mvn install` for verifying that the tests pass, then `git commit` (with a commit message of your choice) and finally `git push`.

**Comment by kelseaflores** [comment]
I've completed the first 4 steps, but how do I overwrite the files in the storage/sis-storage/src/main/java/org/apache/sis/index/tree/ directory with the ones I saved in step 1? I just want to make sure I'm doing it correctly.

**Comment by desruisseaux** [comment]
I suggest to use the command line. Ley say that you saved your work in `/home/mydirectory/backup/`. Then from the directory containing the new clone:

```
cd storage/sis-storage/src/main/java/org/apache/sis/index/tree/
cp /home/mydirectory/backup/*.java .
```

The commands may be different on Windows (I think it is `chdir` instead of `cd`, maybe `copy` instead of `cp`).

**Comment by kelseaflores** [comment]
I've overwritten the files and executed "git add -u", but when I execute "mvn install", the tests fail.

**Comment by desruisseaux** [comment]
Can you post the error message? Not necessarily the whole Maven output, but at least the lines having the [ERROR] header.

**Comment by kelseaflores** [comment]
Here are the lines with the [ERROR] header: 

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/kelseaflores/Desktop/summer_project/sis/storage/sis-storage/src/main/java/org/apache/sis/index/tree). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by desruisseaux** [comment]
The `mvn install` command should be executed from the `/Users/kelseaflores/Desktop/summer_project/sis/` directory. More generally, it needs to be executed from a directory containing a `pom.xml` file (it can be the `storage/sis-storage/` sub-directory if you do not want to build the whole project).

**Comment by kelseaflores** [comment]
When i ran it from /Users/kelseaflores/Desktop/summer_project/sis/, the tests still fail. Here are the error messages: 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (default) on project sis-storage: You have 11 Checkstyle violations. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sis-storage

**Comment by desruisseaux** [comment]
On top of those error messages, you should have a list of files where checkstyle violations occurred. It may be minor things like trailing spaces at end of lines. It may seems exaggerated to make the build fail for such a minor thing as extraneous space at end of lines, but the reason for that is that spaces added or removed at end of line looks invisible in the editor, but are still identified by source versioning system (Git, SVN, …) as a change. So this requirement avoid to have lines falsely flagged as modified when developers commit.

**Comment by kelseaflores** [comment]
I figured out what the violations were. When I was reformatting the indentations in the files from 2 spaces to 4, Eclipse made the 4 spaces into tabs. I tried changing the formatting preferences in Eclipse so that the tabs are replaced with 4 spaces, but my preference changes are not being applied to the code.

**Comment by desruisseaux** [comment]
You may try to indent the code by 4 more spaces, then de-indent it. It may work.

**Comment by kelseaflores** [comment]
The tests are passing now. I went to each file and manually replaced all of the tabs with 4 spaces.

**Comment by desruisseaux** [comment]
You pushed at which URL? The commit that I see at https://github.com/kelseaflores/sis/commit/d55b9b85ba1988748ff18697dba49d8a8ce4b40c seems to be something else. Does `git status` said "nothing to commit (working directory clean)"?

**Comment by kelseaflores** [comment]
"Git status" says: 
nothing added to commit but untracked files present (use "git add" to track)

**Comment by desruisseaux** [comment]
When clicking on the "commit" button, we can see a commit named _"Committing formatting changes - replacing 2 space indentations with 4 space indentations"_. But when clicking on that commit, what we see (the link posted in my previous comment) seems another work.

What are the untracked files listed by Git? And what is the output of `git log`? (only the 2 or 3 first records).

**Comment by kelseaflores** [comment]
All of the untracked files were all of the other files and directories in my Desktop directory. 

And the output of "git log" is: 

commit d55b9b85ba1988748ff18697dba49d8a8ce4b40c
Author: Kelsea Flores <kjflores2@usfca.edu>
Date:   Sun Aug 12 12:19:58 2018 -0700

    Committing formatting changes - replacing 2 space indentations with 4 space indenations

commit 29ffb6e9408fbd679aaaf7973e6db79f461087e5
Merge: 9e8701f f221355
Author: Kelsea Flores <kjflores2@usfca.edu>
Date:   Mon Aug 6 20:12:57 2018 -0700

    Merge https://github.com/apache/sis
    Merging master branch with my local branch.

commit f2213552e7516c40a02968776bb9462ffb928c6a
Merge: 7288315 11d4e97
Author: Martin Desruisseaux <martin.desruisseaux@geomatys.com>
Date:   Mon Aug 6 14:09:24 2018 +0200

    Merge branch 'geoapi-3.1'.

commit 11d4e97d3ee0bc7d6afe5f081ac43081530eda1d

**Comment by desruisseaux** [comment]
It is strange that Git see files of your Desktop directory. Looking at the commits reported by `git log`, I do not see any modification in `sis-storage/…/index/`. I do not see modifications on https://github.com/kelseaflores/sis/tree/master/storage/sis-storage/src/main/java/org/apache/sis/index/tree neither.

Maybe we should try again in another way. From the command line:

```
cd <any sub-directory. Make sure you are in an empty sub-directory>
git clone https://github.com/apache/sis
cd sis
git push --force https://github.com/kelseaflores/sis
```

Note: this will discard your commits, but those commits seem accidental anyway. The intent is to verify that those steps work before to move to next step.

**Comment by kelseaflores** [comment]
Okay, just completed those steps.

**Comment by desruisseaux** [comment]
Now I suggest to open the `storage/sis-storage/src/main/java/org/apache/sis/index/tree` folder and copy there the classes that you modified. After the copy, the following command should give a list of modified Java files:

```
git status
```

**Comment by desruisseaux** [comment]
Thanks. Then we can try:

```
git add -u
git commit -m "<the message>"
git push
```

After those command have been executed, we should see the modified files [in your repository](https://github.com/kelseaflores/sis/tree/master/storage/sis-storage/src/main/java/org/apache/sis/index/tree). At that point we can try a new merge request again.

**Comment by kelseaflores** [comment]
When I executed "git push" it said: 
remote: Permission to apache/sis.git denied to kelseaflores.
fatal: unable to access 'https://github.com/apache/sis/': The requested URL returned error: 403

So I executed "git push https://github.com/kelseaflores/sis" and it said: 
Everything up-to-date

Does that mean my modified files were correctly pushed to GitHub?

**Comment by desruisseaux** [comment]
I still do not see the file on GitHub. What does `git branch` said? Then `git status`?

**Comment by kelseaflores** [comment]
"git branch" is saying: * master

"git status" is saying: 
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	QuadTree.java
	QuadTreeData.java
	QuadTreeNode.java
	QuadTreeWriter.java

nothing added to commit but untracked files present (use "git add" to track)

**Comment by desruisseaux** [comment]
In which directory are those files? Are they in the root directory (I mean, do you see `LICENSE` and `NOTICE` files in the same directory than `QuadTree.java`, `QuadTreeNode.java`, _etc._)?

**Comment by kelseaflores** [comment]
Yes, I see LICENSE and NOTICE files in the same directory. Are the files in the wrong directory?

**Comment by desruisseaux** [comment]
Yes, the files need to be moved. You can do that with the following command:

```
mv *.java storage/sis-storage/src/main/java/org/apache/sis/index/tree/
```

Then ```git status``` should list those files as _modified_ files (as opposed to untracked files). This is because we replaced existing files (which were already tracked) by the new ones. You can then execute ```git add -u```, then ```git status``` again. The files should not be listed as files staged for commit. Before to commit, I suggest to run ```mvn install``` for making sure that tests pass. Then ```git commit``` and ```git push``` to your repository as you did before.

**Comment by kelseaflores** [comment]
The tests passed and I was able to push my code to GitHub!

**Comment by desruisseaux** [comment]
Cool! I can see your work on https://github.com/kelseaflores/sis/tree/master/storage/sis-storage/src/main/java/org/apache/sis/index/tree :) Then you can close this pull request and create a new one.

**Comment by kelseaflores** [comment]
Doing that now. Thank you so much for helping me through that!

**Comment by desruisseaux** [comment]
You are welcome, thanks for your contribution!
(for the record: this merge request is superseded by #10).

**Pull request closed without merging**
