### PR TITLE
Migrate from Maven to Gradle and apply JPMS modularisation

### PR DESCRIPTION
**Pull request by desruisseaux**
This pull request is a major change for Apache SIS developers and for users who compile from source code, but should be transparent for users of the binaries. This pull request contains four inter-dependent tasks:

* Migration from Maven to Gradle build system, necessary because the features implemented by other tasks require more flexibility than what Maven provides.
* Change of source code layout from _Package Hierarchy_ to _Module Source Hierarchy_.
* Replacement of `core`, `storage`, `cloud`, `application`, `profile` groups by a new set of groups: `endorsed`, `incubator` and `optional`.
* Addition of `module-info.java` files for JPMS modularisation.

More details are provided in the [Apache SIS modularisation page](https://geomatys.github.io/draft/Modularization.html) and [announced on the developer mailing list](https://lists.apache.org/thread/xqnydv188cxom22forz3j8bbkbtv8g14). Each commit in this pull request focuses on a specific sub-task.

### CODE REVIEW

**Comment by nknize** [comment]
Could this be done incrementally in two (or more) PRs? Something like:

1. Migrate from Maven to Gradle (no JPMS) 
2. Support JPMS (add `module-info.java`)

**Comment by desruisseaux** [comment]
We could split in separated merge requests, but the migration from Maven to Gradle is very different depending on whether it is done before or after restructuring from _Package Hierarchy_ to _Module Source Hierarchy_. If we migrate to Gradle before, it would be like doing the migration twice given the amount of changes needed in Gradle scripts and plugins (`buildSrc`) after restructuring to Module Source Hierarchy.

Currently the separation is done in commits as below. Those commits are in dependency order, and each of them could be taken as a merge request on its own (git "squash" and "rebase" were done extensively).

1. Cleaning work
    * Remove the NetBeans Ant project
    * Remove test JAR files. Consequently tests cannot be executed anymore (temporarily)
2. Partial JPMS
    * Add `module-info.java`. Project can still be executed with Maven, but not tested.
3. Restructuring from Package Hierarchy to Module Source Hierarchy
    * Remove all Maven project files (because they don't work at all with Module Source Hierarchy)
    * Move all Java source files to their new location with no change in any code.
    * Post move cleanup (code changes caused by restructuring are separated in this commit).
4. Migrage from Maven to Gradle.
    * Add Gradle build scripts, adapted to Module Source Hierarchy.
    * Documentation updates (mostly editions in Javadoc).

As seen above, the commits are in 4 groups which could be separated in 4 merge requests. The reason why they are proposed in a single merge request is because the project is temporarily unbuildable and/or untestable during some intermediate steps. The project is back to buildable and testable state only after the last commit (ignoring the documentation updates).

So would it still be better to split in 2 or more merge requests anyway?

**Comment by nknize** [comment]
This is a great explanation. My personal opinion and preference is to have
each commit as a separate PR just to make it easier to follow and track the
changes. Especially as time passes it's kind of nice to go back and see
smaller PRs. I think if the build doesn't pass it's okay? Especially since
main is an unstable snapshot anyway? Just my $0.02.

- Nick

**Comment by desruisseaux** [comment]
Actually splitting this big pull request (PR) seems difficult because the smaller PRs would not be independent. The second PR would need to either wait for the merge of the first PR before to be created (in which case peoples [voting](https://lists.apache.org/thread/w7llc33nglxp0jvmmq186wm52k2wwcd5) cannot see the full picture), or to contain the first PR which would result in the same thing than this PR…

I presume that the goal is to have diffs easier to read. Bellow are the diffs over the ranges of commits for the two main tasks. They show what smaller pull requests would contain:

* [Adding `module-info.java` and removing Maven `pom.xml` files](https://github.com/apache/sis/compare/6e7bc316e92d141faa77e393d09657a3fc6b0612..0d5a57f562fab7c6e825ad03a8f0c3459ffcb56d)
* [Adding Gradle scripts and migrating Maven POJO to Gradle plugin](https://github.com/apache/sis/compare/b8eeb4789171cdef2e782b684fe52c178947079e..70ccdd51e5398ed5727795ae03522b7c98a284fe)

**Comment by nknize** [comment]
What if you switched the order? Don't enable JPMS (e.g., add `module-info.java`) until the very last step (e.g., step 4).

For example,

1. Rote refactor the classes to a "module hierarchy" (e.g., no split packages so JPMS will be happy in the end)
2. Cleaning Work
3. Migrate from Maven to Gradle
4. Enable JPMS.

The rote refactor shouldn't break any builds? Maybe the cleaning work does because you're removing ANT? In which case you could merge 2 and 3? Remove ANT while migrating from Maven to Gradle. Lastly, JPMS doesn't have to be enabled until gradle build passes. By then all of your classes should be in distinct packages so adding the `module-info.java` files shouldn't do anything other than enable the module system.

**Comment by desruisseaux** [comment]
The refactoring that we could do without breaking the build were already done. It was the topic of #34. When I was working on modularisation, I was preparing those two merge requests simultaneously with lot of "git rebase" and squashes. This merge request contains commits that couldn't be moved to the "pre-migration" phase.

The reason why JPMS had to be done before Gradle migration is because the _Module Source Hierarchy_ is not just about resolving package name clashes. It is a more disruptive feature, supported by standard Java tools since Java 9 but not well known, maybe because neither Gradle or Maven supports it (but Gradle flexibility makes possible to get it working anyway). Module Source Hierarchy is explained briefly in the [Directory Hierarchies](https://docs.oracle.com/en/java/javase/20/docs/specs/man/javac.html#directory-hierarchies) section of Oracle's documentation. I tried to explain more in section 1 of [Java Module Source Hierarchy in a Gradle sub-project](https://geomatys.github.io/draft/Modularization.html) page. Finally I opened issue https://github.com/gradle/gradle/issues/25974 for better support of this feature. It is the application of Module Source Hierarchy, not the addition of `module-info.java` files, which implies a very different way to build the Gradle scripts. So JPMS cannot be moved after Gradle migration, because the migration work is too different depending if done before or after Module Source Hierarchy.

**Comment by desruisseaux** [comment]
This task is recorded in JIRA issue https://issues.apache.org/jira/browse/SIS-582.

**Pull request merged**
